# Generated by Django 3.1.2 on 2020-11-15 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_pat', models.CharField(max_length=100)),
                ('apellido_mat', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administrativo',
            },
        ),
        migrations.CreateModel(
            name='EspacioComun',
            fields=[
                ('id_espacio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'espacio_comun',
            },
        ),
        migrations.CreateModel(
            name='GastoComun',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'gasto_comun',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_pat', models.CharField(max_length=100)),
                ('apellido_mat', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('morosidad', models.BooleanField()),
                ('habilitado', models.BooleanField()),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'residente',
            },
        ),
        migrations.CreateModel(
            name='TipoAdministrativo',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tipo_administrativo',
            },
        ),
        migrations.CreateModel(
            name='TipoEspacioComun',
            fields=[
                ('id_tipo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_espacio_comun',
            },
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_reporte',
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('residente_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.residente')),
            ],
            options={
                'db_table': 'vivienda',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('horario', models.DateField()),
                ('administrativo_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.administrativo')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.DateTimeField()),
                ('estado', models.BooleanField()),
                ('id_espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.espaciocomun')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.pago')),
                ('residente_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.residente')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=400)),
                ('residente_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.residente')),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.tiporeporte')),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=400)),
                ('id_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.gastocomun')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id_multa', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('estado', models.BooleanField()),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.pago')),
                ('residente_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.residente')),
            ],
            options={
                'db_table': 'multa',
            },
        ),
        migrations.AddField(
            model_name='gastocomun',
            name='id_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.pago'),
        ),
        migrations.AddField(
            model_name='gastocomun',
            name='residente_rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.residente'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=400)),
                ('administrativo_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.administrativo')),
            ],
            options={
                'db_table': 'evento',
            },
        ),
        migrations.AddField(
            model_name='espaciocomun',
            name='id_tipo_espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.tipoespaciocomun'),
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=400)),
                ('administrativo_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.administrativo')),
            ],
            options={
                'db_table': 'anuncio',
            },
        ),
        migrations.AddField(
            model_name='administrativo',
            name='tipo_administrativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.tipoadministrativo'),
        ),
    ]
