# Generated by Django 3.1.1 on 2020-11-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_pat', models.CharField(max_length=100)),
                ('apellido_mat', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'administrativo',
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_pat', models.CharField(max_length=100)),
                ('apellido_mat', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('morosidad', models.BooleanField()),
                ('habilitado', models.BooleanField()),
            ],
            options={
                'db_table': 'residente',
            },
        ),
        migrations.CreateModel(
            name='TipoAdministrativo',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tipo_administrativo',
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('residente_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.residente')),
            ],
            options={
                'db_table': 'vivienda',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('horario', models.DateField()),
                ('administrativo_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.administrativo')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=400)),
                ('administrativo_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.administrativo')),
            ],
            options={
                'db_table': 'evento',
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=400)),
                ('administrativo_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.administrativo')),
            ],
            options={
                'db_table': 'anuncio',
            },
        ),
        migrations.AddField(
            model_name='administrativo',
            name='tipo_administrativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.tipoadministrativo'),
        ),
    ]
