# Generated by Django 3.1.1 on 2020-11-12 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('espacioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioComun',
            fields=[
                ('id_espacio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'espacio_comun',
            },
        ),
        migrations.CreateModel(
            name='GastoComun',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'gasto_comun',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='TipoEspacioComun',
            fields=[
                ('id_tipo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_espacio_comun',
            },
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_reporte',
            },
        ),
        migrations.AddField(
            model_name='residente',
            name='usuario_django',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.DateTimeField()),
                ('estado', models.BooleanField()),
                ('id_espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.espaciocomun')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.pago')),
                ('residente_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.residente')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=400)),
                ('residente_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.residente')),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.tiporeporte')),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=400)),
                ('id_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.gastocomun')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id_multa', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('estado', models.BooleanField()),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.pago')),
                ('residente_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.residente')),
            ],
            options={
                'db_table': 'multa',
            },
        ),
        migrations.AddField(
            model_name='gastocomun',
            name='id_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.pago'),
        ),
        migrations.AddField(
            model_name='gastocomun',
            name='residente_rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.residente'),
        ),
        migrations.AddField(
            model_name='espaciocomun',
            name='id_tipo_espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacioApp.tipoespaciocomun'),
        ),
    ]
