# Generated by Django 3.1.1 on 2020-11-13 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('espacioApp', '0002_auto_20201112_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residente',
            old_name='usuario_django',
            new_name='django_user',
        ),
        migrations.AddField(
            model_name='administrativo',
            name='django_user',
            field=models.OneToOneField(default=300, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
